---
apiVersion: clusters.tmc.cloud.vmware.com/v1alpha1
kind: Extension
metadata:
  name: fluent-bit
  namespace: tanzu-system-logging
  annotations:
    tmc.cloud.vmware.com/managed: "false"
spec:
  description: fluent-bit
  version: "v1.6.9_vmware.1"
  name: fluent-bit
  namespace: tanzu-system-logging
  deploymentStrategy:
    type: KUBERNETES_NATIVE
  objects: |
    apiVersion: kappctrl.k14s.io/v1alpha1
    kind: App
    metadata:
      name: fluent-bit
      annotations:
        tmc.cloud.vmware.com/orphan-resource: "true"
    spec:
      syncPeriod: 5m
      serviceAccountName: fluent-bit-extension-sa
      fetch:
        - image:
            url: projects.registry.vmware.com/tkg/tkg-extensions-templates:v1.3.0_vmware.1 
      template:
        - ytt:
            paths:
              - tkg-extensions/common
              - tkg-extensions/logging/fluent-bit
            inline:
              paths:
                update-config-map.yaml: |
                  #@ load("@ytt:overlay", "overlay")
                  #@overlay/match by=overlay.subset({"kind": "ConfigMap", "metadata": {"name": "fluent-bit-config"}})
                  ---
                  data:
                    output-elasticsearch.conf: |
                      [OUTPUT]
                          Name syslog
                          Match *
                          Host 172.19.16.150
                          Port 514
                          Mode tcp
                          Syslog_Format rfc5424
                          Syslog_Hostname_key tkg_cluster
                          Syslog_Appname_key pod_name
                          Syslog_Procid_key container_name
                          Syslog_Message_key message
                          Syslog_sd_key dockerid=docker_id
              pathsFrom:
                - secretRef:
                    name: fluent-bit-data-values
      deploy:
        - kapp:
            rawOptions: ["--wait-timeout=5m"]
